import 'dotenv/config';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';

/**
 * Standalone migration runner. Used locally (`npm run db:migrate`) and on Render
 * deploy (pre-start). Applies the SQL migrations generated by drizzle-kit into ./drizzle.
 */
async function main(): Promise<void> {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error('DATABASE_URL is required to run migrations');
  }
  const pool = new Pool({ connectionString });
  const db = drizzle(pool);

  console.log('Running migrations from ./drizzle ...');
  await migrate(db, { migrationsFolder: './drizzle' });
  await pool.end();

  console.log('Migrations complete.');
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('Migration failed:', err);
    process.exit(1);
  });
